version: "3.8"
services:
  esp32-gesture-mqtt:
    build: .
    container_name: esp32-gesture-mqtt
    environment:
<<<<<<< HEAD
      SOURCE_URL: ${SOURCE_URL}
      VERBOSE: ${VERBOSE}
      TARGET_FPS: ${TARGET_FPS}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_BASE_TOPIC: ${MQTT_BASE_TOPIC}
      MQTT_DISCOVERY_PREFIX: ${MQTT_DISCOVERY_PREFIX}
      PINCH_DEADZONE_PX: ${PINCH_DEADZONE_PX}
      PINCH_HISTORY: ${PINCH_HISTORY}
      CUSTOM_GESTURE_MAP: ${CUSTOM_GESTURE_MAP}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
=======
      SOURCE_URL: "http://192.168.1.24/stream"
      VERBOSE: "1"
      TARGET_FPS: "25"
      MQTT_HOST: "192.168.1.100"
      MQTT_PORT: "1883"
      MQTT_USER: "mqtt_user"
      MQTT_PASSWORD: "Casafiga94?"
      MQTT_BASE_TOPIC: "gesture32"
      MQTT_DISCOVERY_PREFIX: "homeassistant"
      PINCH_DEADZONE_PX: "8"
      PINCH_HISTORY: "8"
      CUSTOM_GESTURE_MAP: "{}"
      PYTHONUNBUFFERED: "1"
>>>>>>> ef27f72 (ritorno alle origini)
    ports:
      - "12345:12345"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:12345/health"]
      interval: 20s
      timeout: 8s
      retries: 5
      start_period: 30s
